# Generated by Django 4.2.6 on 2023-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False),
        ),
    ]
